server:
  port: 7070
spring:
  application:
    name: librarian
  thymeleaf:
    cache: false
    mode: HTML
management:
   endpoints:
      web:
         base-path: /manage
         exposure:
            include: health,info,env,mappings,refresh,loggers,configInspector,configprops,actuators
logging.config: classpath:log4j2-spring.xml
---
spring.config.activate.on-profile: devel
logging.config: classpath:log4j2-spring-devel.xml
