server:
  port: 7070
spring:
  thymeleaf:
    cache: false
    mode: HTML
  h2:
    console:
        enabled: true
        path: /h2-console
  jpa:
    properties:
      hibernate:
        generate_statistics: true        
        jdbc:
          batch_size: 1000
    open-in-view: false
management:
   endpoints:
      web:
         base-path: /manage
         exposure:
            include: health,info,env,mappings,loggers,configInspector,configprops,actuators
logging.config: classpath:log4j2-spring.xml
---
spring:
   profiles: devel
logging.config: classpath:log4j2-spring-devel.xml
  