server:
  port: 7070
spring:
  thymeleaf:
    cache: false
    mode: HTML
management:
   endpoints:
      web:
         base-path: /manage
         exposure:
            include: health,info,env,mappings,loggers,configInspector,configprops,actuators
logging.config: classpath:log4j2-spring.xml
---
spring:
   profiles: devel
logging.config: classpath:log4j2-spring-devel.xml
  