# This workflow will create a new release when it is called

name: Create release

on: 
  workflow_dispatch:
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Find out versio
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
         PROJECT_VERSION=`mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive  exec:exec`
         CLEAN_PROJECT_VERSION=`echo "${RELEASE_VERSION%-SNAPSHOT}"`
         echo "Version ${RELEASE_VERSION} y reconocida ${CLEAN_PROJECT_VERSION}"