# This workflow will update the links to the latest n releases when it is called

name: Update README

on: 
  workflow_dispatch:
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Configure git for the maven release plugin
      run: |
        git config --global committer.email "noreply@github.com"
        git config --global committer.name "GitHub"
        git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global author.name "${GITHUB_ACTOR}"
        
    - name: Update README.md file
      run: |
        LINKS=`curl -s -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer 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" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Verdoso/epl_librarian/releases \
          | grep tag_name \
          | sed -E 's|"tag_name": "(Release_Tag_v([^"]+))",|\\* Release \2: https://github.com/Verdoso/epl_librarian/releases/tag/\1\\\\n|' \
          | paste -sd ''`
        sed -e "/BEGIN/,/END/c\[//]: # (BEGIN)\n$LINKS\n[//]: # (END)" README.md
